#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="workSearсher")]
	public partial class dataClassWorkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcoobec(coobec instance);
    partial void Updatecoobec(coobec instance);
    partial void Deletecoobec(coobec instance);
    partial void Insertvzdelan(vzdelan instance);
    partial void Updatevzdelan(vzdelan instance);
    partial void Deletevzdelan(vzdelan instance);
    partial void Insertfile(file instance);
    partial void Updatefile(file instance);
    partial void Deletefile(file instance);
    partial void Insertjazyk(jazyk instance);
    partial void Updatejazyk(jazyk instance);
    partial void Deletejazyk(jazyk instance);
    partial void Insertobec(obec instance);
    partial void Updateobec(obec instance);
    partial void Deleteobec(obec instance);
    partial void Insertobor(obor instance);
    partial void Updateobor(obor instance);
    partial void Deleteobor(obor instance);
    partial void Insertokre(okre instance);
    partial void Updateokre(okre instance);
    partial void Deleteokre(okre instance);
    partial void InsertpracVztah(pracVztah instance);
    partial void UpdatepracVztah(pracVztah instance);
    partial void DeletepracVztah(pracVztah instance);
    partial void Insertprof(prof instance);
    partial void Updateprof(prof instance);
    partial void Deleteprof(prof instance);
    partial void Insertsmeny(smeny instance);
    partial void Updatesmeny(smeny instance);
    partial void Deletesmeny(smeny instance);
    partial void InserttypZamest(typZamest instance);
    partial void UpdatetypZamest(typZamest instance);
    partial void DeletetypZamest(typZamest instance);
    partial void InserturadPrace(uradPrace instance);
    partial void UpdateuradPrace(uradPrace instance);
    partial void DeleteuradPrace(uradPrace instance);
    partial void InsertrelVmJazyk(relVmJazyk instance);
    partial void UpdaterelVmJazyk(relVmJazyk instance);
    partial void DeleterelVmJazyk(relVmJazyk instance);
    partial void InsertrelVmTypZ(relVmTypZ instance);
    partial void UpdaterelVmTypZ(relVmTypZ instance);
    partial void DeleterelVmTypZ(relVmTypZ instance);
    partial void InsertVM(VM instance);
    partial void UpdateVM(VM instance);
    partial void DeleteVM(VM instance);
    #endregion
		
		public dataClassWorkDataContext() : 
				base(global::DataModel.Properties.Settings.Default.connectString, mappingSource)
		{
			OnCreated();
		}
		
		public dataClassWorkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataClassWorkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataClassWorkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataClassWorkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<coobec> coobecs
		{
			get
			{
				return this.GetTable<coobec>();
			}
		}
		
		public System.Data.Linq.Table<vzdelan> vzdelans
		{
			get
			{
				return this.GetTable<vzdelan>();
			}
		}
		
		public System.Data.Linq.Table<file> files
		{
			get
			{
				return this.GetTable<file>();
			}
		}
		
		public System.Data.Linq.Table<jazyk> jazyks
		{
			get
			{
				return this.GetTable<jazyk>();
			}
		}
		
		public System.Data.Linq.Table<obec> obecs
		{
			get
			{
				return this.GetTable<obec>();
			}
		}
		
		public System.Data.Linq.Table<obor> obors
		{
			get
			{
				return this.GetTable<obor>();
			}
		}
		
		public System.Data.Linq.Table<okre> okres
		{
			get
			{
				return this.GetTable<okre>();
			}
		}
		
		public System.Data.Linq.Table<pracVztah> pracVztahs
		{
			get
			{
				return this.GetTable<pracVztah>();
			}
		}
		
		public System.Data.Linq.Table<prof> profs
		{
			get
			{
				return this.GetTable<prof>();
			}
		}
		
		public System.Data.Linq.Table<smeny> smenies
		{
			get
			{
				return this.GetTable<smeny>();
			}
		}
		
		public System.Data.Linq.Table<typZamest> typZamests
		{
			get
			{
				return this.GetTable<typZamest>();
			}
		}
		
		public System.Data.Linq.Table<uradPrace> uradPraces
		{
			get
			{
				return this.GetTable<uradPrace>();
			}
		}
		
		public System.Data.Linq.Table<relVmJazyk> relVmJazyks
		{
			get
			{
				return this.GetTable<relVmJazyk>();
			}
		}
		
		public System.Data.Linq.Table<relVmTypZ> relVmTypZs
		{
			get
			{
				return this.GetTable<relVmTypZ>();
			}
		}
		
		public System.Data.Linq.Table<VM> VMs
		{
			get
			{
				return this.GetTable<VM>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectOkres")]
		public ISingleResult<SelectOkresResult> SelectOkres([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> okres)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), okres);
			return ((ISingleResult<SelectOkresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectJazyk")]
		public ISingleResult<SelectJazykResult> SelectJazyk([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> jazyk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jazyk);
			return ((ISingleResult<SelectJazykResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectObor")]
		public ISingleResult<SelectOborResult> SelectObor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> obor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), obor);
			return ((ISingleResult<SelectOborResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectSmeny")]
		public ISingleResult<SelectSmenyResult> SelectSmeny([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> smeny)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), smeny);
			return ((ISingleResult<SelectSmenyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectVzdelani")]
		public ISingleResult<SelectVzdelaniResult> SelectVzdelani([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> vzdelani)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vzdelani);
			return ((ISingleResult<SelectVzdelaniResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectVM")]
		public ISingleResult<SelectVMResult> SelectVM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VM", DbType="Int")] System.Nullable<int> vM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vM);
			return ((ISingleResult<SelectVMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectProfByObor")]
		public ISingleResult<SelectProfByOborResult> SelectProfByObor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> obor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), obor);
			return ((ISingleResult<SelectProfByOborResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectVMByJazyk")]
		public ISingleResult<SelectVMByJazykResult> SelectVMByJazyk([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> jazyk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jazyk);
			return ((ISingleResult<SelectVMByJazykResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.coobec")]
	public partial class coobec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _psc;
		
		private int _idObec;
		
		private EntityRef<obec> _obec;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpscChanging(string value);
    partial void OnpscChanged();
    partial void OnidObecChanging(int value);
    partial void OnidObecChanged();
    #endregion
		
		public coobec()
		{
			this._obec = default(EntityRef<obec>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_psc", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string psc
		{
			get
			{
				return this._psc;
			}
			set
			{
				if ((this._psc != value))
				{
					this.OnpscChanging(value);
					this.SendPropertyChanging();
					this._psc = value;
					this.SendPropertyChanged("psc");
					this.OnpscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idObec", DbType="Int NOT NULL")]
		public int idObec
		{
			get
			{
				return this._idObec;
			}
			set
			{
				if ((this._idObec != value))
				{
					if (this._obec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidObecChanging(value);
					this.SendPropertyChanging();
					this._idObec = value;
					this.SendPropertyChanged("idObec");
					this.OnidObecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="obec_coobec", Storage="_obec", ThisKey="idObec", OtherKey="id", IsForeignKey=true)]
		public obec obec
		{
			get
			{
				return this._obec.Entity;
			}
			set
			{
				obec previousValue = this._obec.Entity;
				if (((previousValue != value) 
							|| (this._obec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._obec.Entity = null;
						previousValue.coobecs.Remove(this);
					}
					this._obec.Entity = value;
					if ((value != null))
					{
						value.coobecs.Add(this);
						this._idObec = value.id;
					}
					else
					{
						this._idObec = default(int);
					}
					this.SendPropertyChanged("obec");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vzdelan")]
	public partial class vzdelan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _kodUP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnkodUPChanging(string value);
    partial void OnkodUPChanged();
    #endregion
		
		public vzdelan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(250)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodUP", DbType="NVarChar(30)")]
		public string kodUP
		{
			get
			{
				return this._kodUP;
			}
			set
			{
				if ((this._kodUP != value))
				{
					this.OnkodUPChanging(value);
					this.SendPropertyChanging();
					this._kodUP = value;
					this.SendPropertyChanged("kodUP");
					this.OnkodUPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.files")]
	public partial class file : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public file()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jazyk")]
	public partial class jazyk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _kodUP;
		
		private string _name;
		
		private string _uroven;
		
		private string _urovenId;
		
		private EntitySet<relVmJazyk> _relVmJazyks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkodUPChanging(string value);
    partial void OnkodUPChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnurovenChanging(string value);
    partial void OnurovenChanged();
    partial void OnurovenIdChanging(string value);
    partial void OnurovenIdChanged();
    #endregion
		
		public jazyk()
		{
			this._relVmJazyks = new EntitySet<relVmJazyk>(new Action<relVmJazyk>(this.attach_relVmJazyks), new Action<relVmJazyk>(this.detach_relVmJazyks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodUP", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string kodUP
		{
			get
			{
				return this._kodUP;
			}
			set
			{
				if ((this._kodUP != value))
				{
					this.OnkodUPChanging(value);
					this.SendPropertyChanging();
					this._kodUP = value;
					this.SendPropertyChanged("kodUP");
					this.OnkodUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uroven", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string uroven
		{
			get
			{
				return this._uroven;
			}
			set
			{
				if ((this._uroven != value))
				{
					this.OnurovenChanging(value);
					this.SendPropertyChanging();
					this._uroven = value;
					this.SendPropertyChanged("uroven");
					this.OnurovenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urovenId", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string urovenId
		{
			get
			{
				return this._urovenId;
			}
			set
			{
				if ((this._urovenId != value))
				{
					this.OnurovenIdChanging(value);
					this.SendPropertyChanging();
					this._urovenId = value;
					this.SendPropertyChanged("urovenId");
					this.OnurovenIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jazyk_relVmJazyk", Storage="_relVmJazyks", ThisKey="id", OtherKey="idJazyk")]
		public EntitySet<relVmJazyk> relVmJazyks
		{
			get
			{
				return this._relVmJazyks;
			}
			set
			{
				this._relVmJazyks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_relVmJazyks(relVmJazyk entity)
		{
			this.SendPropertyChanging();
			entity.jazyk = this;
		}
		
		private void detach_relVmJazyks(relVmJazyk entity)
		{
			this.SendPropertyChanging();
			entity.jazyk = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.obec")]
	public partial class obec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private int _idOkres;
		
		private EntitySet<coobec> _coobecs;
		
		private EntityRef<okre> _okre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnidOkresChanging(int value);
    partial void OnidOkresChanged();
    #endregion
		
		public obec()
		{
			this._coobecs = new EntitySet<coobec>(new Action<coobec>(this.attach_coobecs), new Action<coobec>(this.detach_coobecs));
			this._okre = default(EntityRef<okre>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOkres", DbType="Int NOT NULL")]
		public int idOkres
		{
			get
			{
				return this._idOkres;
			}
			set
			{
				if ((this._idOkres != value))
				{
					if (this._okre.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidOkresChanging(value);
					this.SendPropertyChanging();
					this._idOkres = value;
					this.SendPropertyChanged("idOkres");
					this.OnidOkresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="obec_coobec", Storage="_coobecs", ThisKey="id", OtherKey="idObec")]
		public EntitySet<coobec> coobecs
		{
			get
			{
				return this._coobecs;
			}
			set
			{
				this._coobecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="okre_obec", Storage="_okre", ThisKey="idOkres", OtherKey="id", IsForeignKey=true)]
		public okre okre
		{
			get
			{
				return this._okre.Entity;
			}
			set
			{
				okre previousValue = this._okre.Entity;
				if (((previousValue != value) 
							|| (this._okre.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._okre.Entity = null;
						previousValue.obecs.Remove(this);
					}
					this._okre.Entity = value;
					if ((value != null))
					{
						value.obecs.Add(this);
						this._idOkres = value.id;
					}
					else
					{
						this._idOkres = default(int);
					}
					this.SendPropertyChanged("okre");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_coobecs(coobec entity)
		{
			this.SendPropertyChanging();
			entity.obec = this;
		}
		
		private void detach_coobecs(coobec entity)
		{
			this.SendPropertyChanging();
			entity.obec = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.obor")]
	public partial class obor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _kodUp;
		
		private EntitySet<prof> _profs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnkodUpChanging(string value);
    partial void OnkodUpChanged();
    #endregion
		
		public obor()
		{
			this._profs = new EntitySet<prof>(new Action<prof>(this.attach_profs), new Action<prof>(this.detach_profs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodUp", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string kodUp
		{
			get
			{
				return this._kodUp;
			}
			set
			{
				if ((this._kodUp != value))
				{
					this.OnkodUpChanging(value);
					this.SendPropertyChanging();
					this._kodUp = value;
					this.SendPropertyChanged("kodUp");
					this.OnkodUpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="obor_prof", Storage="_profs", ThisKey="id", OtherKey="idObor")]
		public EntitySet<prof> profs
		{
			get
			{
				return this._profs;
			}
			set
			{
				this._profs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_profs(prof entity)
		{
			this.SendPropertyChanging();
			entity.obor = this;
		}
		
		private void detach_profs(prof entity)
		{
			this.SendPropertyChanging();
			entity.obor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.okres")]
	public partial class okre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _kodUP;
		
		private EntitySet<obec> _obecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnkodUPChanging(string value);
    partial void OnkodUPChanged();
    #endregion
		
		public okre()
		{
			this._obecs = new EntitySet<obec>(new Action<obec>(this.attach_obecs), new Action<obec>(this.detach_obecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodUP", DbType="NVarChar(30)")]
		public string kodUP
		{
			get
			{
				return this._kodUP;
			}
			set
			{
				if ((this._kodUP != value))
				{
					this.OnkodUPChanging(value);
					this.SendPropertyChanging();
					this._kodUP = value;
					this.SendPropertyChanged("kodUP");
					this.OnkodUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="okre_obec", Storage="_obecs", ThisKey="id", OtherKey="idOkres")]
		public EntitySet<obec> obecs
		{
			get
			{
				return this._obecs;
			}
			set
			{
				this._obecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_obecs(obec entity)
		{
			this.SendPropertyChanging();
			entity.okre = this;
		}
		
		private void detach_obecs(obec entity)
		{
			this.SendPropertyChanging();
			entity.okre = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pracVztah")]
	public partial class pracVztah : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _kod;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnkodChanging(string value);
    partial void OnkodChanged();
    #endregion
		
		public pracVztah()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kod
		{
			get
			{
				return this._kod;
			}
			set
			{
				if ((this._kod != value))
				{
					this.OnkodChanging(value);
					this.SendPropertyChanging();
					this._kod = value;
					this.SendPropertyChanged("kod");
					this.OnkodChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.prof")]
	public partial class prof : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _kodUP;
		
		private int _idObor;
		
		private EntitySet<VM> _VMs;
		
		private EntityRef<obor> _obor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnkodUPChanging(string value);
    partial void OnkodUPChanged();
    partial void OnidOborChanging(int value);
    partial void OnidOborChanged();
    #endregion
		
		public prof()
		{
			this._VMs = new EntitySet<VM>(new Action<VM>(this.attach_VMs), new Action<VM>(this.detach_VMs));
			this._obor = default(EntityRef<obor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(250)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodUP", DbType="NVarChar(30)")]
		public string kodUP
		{
			get
			{
				return this._kodUP;
			}
			set
			{
				if ((this._kodUP != value))
				{
					this.OnkodUPChanging(value);
					this.SendPropertyChanging();
					this._kodUP = value;
					this.SendPropertyChanged("kodUP");
					this.OnkodUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idObor", DbType="Int NOT NULL")]
		public int idObor
		{
			get
			{
				return this._idObor;
			}
			set
			{
				if ((this._idObor != value))
				{
					if (this._obor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidOborChanging(value);
					this.SendPropertyChanging();
					this._idObor = value;
					this.SendPropertyChanged("idObor");
					this.OnidOborChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="prof_VM", Storage="_VMs", ThisKey="id", OtherKey="idProf")]
		public EntitySet<VM> VMs
		{
			get
			{
				return this._VMs;
			}
			set
			{
				this._VMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="obor_prof", Storage="_obor", ThisKey="idObor", OtherKey="id", IsForeignKey=true)]
		public obor obor
		{
			get
			{
				return this._obor.Entity;
			}
			set
			{
				obor previousValue = this._obor.Entity;
				if (((previousValue != value) 
							|| (this._obor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._obor.Entity = null;
						previousValue.profs.Remove(this);
					}
					this._obor.Entity = value;
					if ((value != null))
					{
						value.profs.Add(this);
						this._idObor = value.id;
					}
					else
					{
						this._idObor = default(int);
					}
					this.SendPropertyChanged("obor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VMs(VM entity)
		{
			this.SendPropertyChanging();
			entity.prof = this;
		}
		
		private void detach_VMs(VM entity)
		{
			this.SendPropertyChanging();
			entity.prof = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.smeny")]
	public partial class smeny : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _kodUP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnkodUPChanging(string value);
    partial void OnkodUPChanged();
    #endregion
		
		public smeny()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodUP", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string kodUP
		{
			get
			{
				return this._kodUP;
			}
			set
			{
				if ((this._kodUP != value))
				{
					this.OnkodUPChanging(value);
					this.SendPropertyChanging();
					this._kodUP = value;
					this.SendPropertyChanged("kodUP");
					this.OnkodUPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.typZamest")]
	public partial class typZamest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _kod;
		
		private EntitySet<relVmTypZ> _relVmTypZs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnkodChanging(string value);
    partial void OnkodChanged();
    #endregion
		
		public typZamest()
		{
			this._relVmTypZs = new EntitySet<relVmTypZ>(new Action<relVmTypZ>(this.attach_relVmTypZs), new Action<relVmTypZ>(this.detach_relVmTypZs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kod
		{
			get
			{
				return this._kod;
			}
			set
			{
				if ((this._kod != value))
				{
					this.OnkodChanging(value);
					this.SendPropertyChanging();
					this._kod = value;
					this.SendPropertyChanged("kod");
					this.OnkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="typZamest_relVmTypZ", Storage="_relVmTypZs", ThisKey="id", OtherKey="idTypZ")]
		public EntitySet<relVmTypZ> relVmTypZs
		{
			get
			{
				return this._relVmTypZs;
			}
			set
			{
				this._relVmTypZs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_relVmTypZs(relVmTypZ entity)
		{
			this.SendPropertyChanging();
			entity.typZamest = this;
		}
		
		private void detach_relVmTypZs(relVmTypZ entity)
		{
			this.SendPropertyChanging();
			entity.typZamest = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uradPrace")]
	public partial class uradPrace : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _kodUP;
		
		private EntitySet<VM> _VMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnkodUPChanging(string value);
    partial void OnkodUPChanged();
    #endregion
		
		public uradPrace()
		{
			this._VMs = new EntitySet<VM>(new Action<VM>(this.attach_VMs), new Action<VM>(this.detach_VMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodUP", DbType="NVarChar(30)")]
		public string kodUP
		{
			get
			{
				return this._kodUP;
			}
			set
			{
				if ((this._kodUP != value))
				{
					this.OnkodUPChanging(value);
					this.SendPropertyChanging();
					this._kodUP = value;
					this.SendPropertyChanged("kodUP");
					this.OnkodUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="uradPrace_VM", Storage="_VMs", ThisKey="id", OtherKey="idUP")]
		public EntitySet<VM> VMs
		{
			get
			{
				return this._VMs;
			}
			set
			{
				this._VMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VMs(VM entity)
		{
			this.SendPropertyChanging();
			entity.uradPrace = this;
		}
		
		private void detach_VMs(VM entity)
		{
			this.SendPropertyChanging();
			entity.uradPrace = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.relVmJazyk")]
	public partial class relVmJazyk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idVM;
		
		private int _idJazyk;
		
		private EntityRef<jazyk> _jazyk;
		
		private EntityRef<VM> _VM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidVMChanging(int value);
    partial void OnidVMChanged();
    partial void OnidJazykChanging(int value);
    partial void OnidJazykChanged();
    #endregion
		
		public relVmJazyk()
		{
			this._jazyk = default(EntityRef<jazyk>);
			this._VM = default(EntityRef<VM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVM", DbType="Int NOT NULL")]
		public int idVM
		{
			get
			{
				return this._idVM;
			}
			set
			{
				if ((this._idVM != value))
				{
					if (this._VM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidVMChanging(value);
					this.SendPropertyChanging();
					this._idVM = value;
					this.SendPropertyChanged("idVM");
					this.OnidVMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJazyk", DbType="Int NOT NULL")]
		public int idJazyk
		{
			get
			{
				return this._idJazyk;
			}
			set
			{
				if ((this._idJazyk != value))
				{
					if (this._jazyk.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidJazykChanging(value);
					this.SendPropertyChanging();
					this._idJazyk = value;
					this.SendPropertyChanged("idJazyk");
					this.OnidJazykChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jazyk_relVmJazyk", Storage="_jazyk", ThisKey="idJazyk", OtherKey="id", IsForeignKey=true)]
		public jazyk jazyk
		{
			get
			{
				return this._jazyk.Entity;
			}
			set
			{
				jazyk previousValue = this._jazyk.Entity;
				if (((previousValue != value) 
							|| (this._jazyk.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._jazyk.Entity = null;
						previousValue.relVmJazyks.Remove(this);
					}
					this._jazyk.Entity = value;
					if ((value != null))
					{
						value.relVmJazyks.Add(this);
						this._idJazyk = value.id;
					}
					else
					{
						this._idJazyk = default(int);
					}
					this.SendPropertyChanged("jazyk");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VM_relVmJazyk", Storage="_VM", ThisKey="idVM", OtherKey="id", IsForeignKey=true)]
		public VM VM
		{
			get
			{
				return this._VM.Entity;
			}
			set
			{
				VM previousValue = this._VM.Entity;
				if (((previousValue != value) 
							|| (this._VM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VM.Entity = null;
						previousValue.relVmJazyks.Remove(this);
					}
					this._VM.Entity = value;
					if ((value != null))
					{
						value.relVmJazyks.Add(this);
						this._idVM = value.id;
					}
					else
					{
						this._idVM = default(int);
					}
					this.SendPropertyChanged("VM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.relVmTypZ")]
	public partial class relVmTypZ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idVM;
		
		private int _idTypZ;
		
		private EntityRef<typZamest> _typZamest;
		
		private EntityRef<VM> _VM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidVMChanging(int value);
    partial void OnidVMChanged();
    partial void OnidTypZChanging(int value);
    partial void OnidTypZChanged();
    #endregion
		
		public relVmTypZ()
		{
			this._typZamest = default(EntityRef<typZamest>);
			this._VM = default(EntityRef<VM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVM", DbType="Int NOT NULL")]
		public int idVM
		{
			get
			{
				return this._idVM;
			}
			set
			{
				if ((this._idVM != value))
				{
					if (this._VM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidVMChanging(value);
					this.SendPropertyChanging();
					this._idVM = value;
					this.SendPropertyChanged("idVM");
					this.OnidVMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTypZ", DbType="Int NOT NULL")]
		public int idTypZ
		{
			get
			{
				return this._idTypZ;
			}
			set
			{
				if ((this._idTypZ != value))
				{
					if (this._typZamest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTypZChanging(value);
					this.SendPropertyChanging();
					this._idTypZ = value;
					this.SendPropertyChanged("idTypZ");
					this.OnidTypZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="typZamest_relVmTypZ", Storage="_typZamest", ThisKey="idTypZ", OtherKey="id", IsForeignKey=true)]
		public typZamest typZamest
		{
			get
			{
				return this._typZamest.Entity;
			}
			set
			{
				typZamest previousValue = this._typZamest.Entity;
				if (((previousValue != value) 
							|| (this._typZamest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._typZamest.Entity = null;
						previousValue.relVmTypZs.Remove(this);
					}
					this._typZamest.Entity = value;
					if ((value != null))
					{
						value.relVmTypZs.Add(this);
						this._idTypZ = value.id;
					}
					else
					{
						this._idTypZ = default(int);
					}
					this.SendPropertyChanged("typZamest");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VM_relVmTypZ", Storage="_VM", ThisKey="idVM", OtherKey="id", IsForeignKey=true)]
		public VM VM
		{
			get
			{
				return this._VM.Entity;
			}
			set
			{
				VM previousValue = this._VM.Entity;
				if (((previousValue != value) 
							|| (this._VM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VM.Entity = null;
						previousValue.relVmTypZs.Remove(this);
					}
					this._VM.Entity = value;
					if ((value != null))
					{
						value.relVmTypZs.Add(this);
						this._idVM = value.id;
					}
					else
					{
						this._idVM = default(int);
					}
					this.SendPropertyChanged("VM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VM")]
	public partial class VM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _kodUP;
		
		private int _idProf;
		
		private string _firma;
		
		private System.Nullable<int> _idSmena;
		
		private System.Nullable<int> _idVzdelani;
		
		private string _idPracVztah;
		
		private string _idObce;
		
		private string _kontakt;
		
		private System.Nullable<decimal> _mzdaOd;
		
		private System.Nullable<decimal> _mzdaDo;
		
		private string _mzdaType;
		
		private System.Nullable<System.DateTime> _terminOd;
		
		private System.Nullable<System.DateTime> _terminDo;
		
		private int _idUP;
		
		private System.Nullable<int> _modryKarty;
		
		private System.Nullable<int> _zamestnKarty;
		
		private System.Nullable<System.DateTime> _dateAktual;
		
		private int _volnychMist;
		
		private string _poznamka;
		
		private EntitySet<relVmJazyk> _relVmJazyks;
		
		private EntitySet<relVmTypZ> _relVmTypZs;
		
		private EntityRef<prof> _prof;
		
		private EntityRef<uradPrace> _uradPrace;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkodUPChanging(string value);
    partial void OnkodUPChanged();
    partial void OnidProfChanging(int value);
    partial void OnidProfChanged();
    partial void OnfirmaChanging(string value);
    partial void OnfirmaChanged();
    partial void OnidSmenaChanging(System.Nullable<int> value);
    partial void OnidSmenaChanged();
    partial void OnidVzdelaniChanging(System.Nullable<int> value);
    partial void OnidVzdelaniChanged();
    partial void OnidPracVztahChanging(string value);
    partial void OnidPracVztahChanged();
    partial void OnidObceChanging(string value);
    partial void OnidObceChanged();
    partial void OnkontaktChanging(string value);
    partial void OnkontaktChanged();
    partial void OnmzdaOdChanging(System.Nullable<decimal> value);
    partial void OnmzdaOdChanged();
    partial void OnmzdaDoChanging(System.Nullable<decimal> value);
    partial void OnmzdaDoChanged();
    partial void OnmzdaTypeChanging(string value);
    partial void OnmzdaTypeChanged();
    partial void OnterminOdChanging(System.Nullable<System.DateTime> value);
    partial void OnterminOdChanged();
    partial void OnterminDoChanging(System.Nullable<System.DateTime> value);
    partial void OnterminDoChanged();
    partial void OnidUPChanging(int value);
    partial void OnidUPChanged();
    partial void OnmodryKartyChanging(System.Nullable<int> value);
    partial void OnmodryKartyChanged();
    partial void OnzamestnKartyChanging(System.Nullable<int> value);
    partial void OnzamestnKartyChanged();
    partial void OndateAktualChanging(System.Nullable<System.DateTime> value);
    partial void OndateAktualChanged();
    partial void OnvolnychMistChanging(int value);
    partial void OnvolnychMistChanged();
    partial void OnpoznamkaChanging(string value);
    partial void OnpoznamkaChanged();
    #endregion
		
		public VM()
		{
			this._relVmJazyks = new EntitySet<relVmJazyk>(new Action<relVmJazyk>(this.attach_relVmJazyks), new Action<relVmJazyk>(this.detach_relVmJazyks));
			this._relVmTypZs = new EntitySet<relVmTypZ>(new Action<relVmTypZ>(this.attach_relVmTypZs), new Action<relVmTypZ>(this.detach_relVmTypZs));
			this._prof = default(EntityRef<prof>);
			this._uradPrace = default(EntityRef<uradPrace>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodUP", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string kodUP
		{
			get
			{
				return this._kodUP;
			}
			set
			{
				if ((this._kodUP != value))
				{
					this.OnkodUPChanging(value);
					this.SendPropertyChanging();
					this._kodUP = value;
					this.SendPropertyChanged("kodUP");
					this.OnkodUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProf", DbType="Int NOT NULL")]
		public int idProf
		{
			get
			{
				return this._idProf;
			}
			set
			{
				if ((this._idProf != value))
				{
					if (this._prof.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProfChanging(value);
					this.SendPropertyChanging();
					this._idProf = value;
					this.SendPropertyChanged("idProf");
					this.OnidProfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string firma
		{
			get
			{
				return this._firma;
			}
			set
			{
				if ((this._firma != value))
				{
					this.OnfirmaChanging(value);
					this.SendPropertyChanging();
					this._firma = value;
					this.SendPropertyChanged("firma");
					this.OnfirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSmena", DbType="Int")]
		public System.Nullable<int> idSmena
		{
			get
			{
				return this._idSmena;
			}
			set
			{
				if ((this._idSmena != value))
				{
					this.OnidSmenaChanging(value);
					this.SendPropertyChanging();
					this._idSmena = value;
					this.SendPropertyChanged("idSmena");
					this.OnidSmenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVzdelani", DbType="Int")]
		public System.Nullable<int> idVzdelani
		{
			get
			{
				return this._idVzdelani;
			}
			set
			{
				if ((this._idVzdelani != value))
				{
					this.OnidVzdelaniChanging(value);
					this.SendPropertyChanging();
					this._idVzdelani = value;
					this.SendPropertyChanged("idVzdelani");
					this.OnidVzdelaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPracVztah", DbType="NVarChar(50)")]
		public string idPracVztah
		{
			get
			{
				return this._idPracVztah;
			}
			set
			{
				if ((this._idPracVztah != value))
				{
					this.OnidPracVztahChanging(value);
					this.SendPropertyChanging();
					this._idPracVztah = value;
					this.SendPropertyChanged("idPracVztah");
					this.OnidPracVztahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idObce", DbType="NVarChar(30)")]
		public string idObce
		{
			get
			{
				return this._idObce;
			}
			set
			{
				if ((this._idObce != value))
				{
					this.OnidObceChanging(value);
					this.SendPropertyChanging();
					this._idObce = value;
					this.SendPropertyChanged("idObce");
					this.OnidObceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kontakt", DbType="NVarChar(250)")]
		public string kontakt
		{
			get
			{
				return this._kontakt;
			}
			set
			{
				if ((this._kontakt != value))
				{
					this.OnkontaktChanging(value);
					this.SendPropertyChanging();
					this._kontakt = value;
					this.SendPropertyChanged("kontakt");
					this.OnkontaktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzdaOd", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> mzdaOd
		{
			get
			{
				return this._mzdaOd;
			}
			set
			{
				if ((this._mzdaOd != value))
				{
					this.OnmzdaOdChanging(value);
					this.SendPropertyChanging();
					this._mzdaOd = value;
					this.SendPropertyChanged("mzdaOd");
					this.OnmzdaOdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzdaDo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> mzdaDo
		{
			get
			{
				return this._mzdaDo;
			}
			set
			{
				if ((this._mzdaDo != value))
				{
					this.OnmzdaDoChanging(value);
					this.SendPropertyChanging();
					this._mzdaDo = value;
					this.SendPropertyChanged("mzdaDo");
					this.OnmzdaDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzdaType", DbType="NVarChar(10)")]
		public string mzdaType
		{
			get
			{
				return this._mzdaType;
			}
			set
			{
				if ((this._mzdaType != value))
				{
					this.OnmzdaTypeChanging(value);
					this.SendPropertyChanging();
					this._mzdaType = value;
					this.SendPropertyChanged("mzdaType");
					this.OnmzdaTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_terminOd", DbType="Date")]
		public System.Nullable<System.DateTime> terminOd
		{
			get
			{
				return this._terminOd;
			}
			set
			{
				if ((this._terminOd != value))
				{
					this.OnterminOdChanging(value);
					this.SendPropertyChanging();
					this._terminOd = value;
					this.SendPropertyChanged("terminOd");
					this.OnterminOdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_terminDo", DbType="Date")]
		public System.Nullable<System.DateTime> terminDo
		{
			get
			{
				return this._terminDo;
			}
			set
			{
				if ((this._terminDo != value))
				{
					this.OnterminDoChanging(value);
					this.SendPropertyChanging();
					this._terminDo = value;
					this.SendPropertyChanged("terminDo");
					this.OnterminDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUP", DbType="Int NOT NULL")]
		public int idUP
		{
			get
			{
				return this._idUP;
			}
			set
			{
				if ((this._idUP != value))
				{
					if (this._uradPrace.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUPChanging(value);
					this.SendPropertyChanging();
					this._idUP = value;
					this.SendPropertyChanged("idUP");
					this.OnidUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modryKarty", DbType="Int")]
		public System.Nullable<int> modryKarty
		{
			get
			{
				return this._modryKarty;
			}
			set
			{
				if ((this._modryKarty != value))
				{
					this.OnmodryKartyChanging(value);
					this.SendPropertyChanging();
					this._modryKarty = value;
					this.SendPropertyChanged("modryKarty");
					this.OnmodryKartyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zamestnKarty", DbType="Int")]
		public System.Nullable<int> zamestnKarty
		{
			get
			{
				return this._zamestnKarty;
			}
			set
			{
				if ((this._zamestnKarty != value))
				{
					this.OnzamestnKartyChanging(value);
					this.SendPropertyChanging();
					this._zamestnKarty = value;
					this.SendPropertyChanged("zamestnKarty");
					this.OnzamestnKartyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateAktual", DbType="Date")]
		public System.Nullable<System.DateTime> dateAktual
		{
			get
			{
				return this._dateAktual;
			}
			set
			{
				if ((this._dateAktual != value))
				{
					this.OndateAktualChanging(value);
					this.SendPropertyChanging();
					this._dateAktual = value;
					this.SendPropertyChanged("dateAktual");
					this.OndateAktualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volnychMist", DbType="Int NOT NULL")]
		public int volnychMist
		{
			get
			{
				return this._volnychMist;
			}
			set
			{
				if ((this._volnychMist != value))
				{
					this.OnvolnychMistChanging(value);
					this.SendPropertyChanging();
					this._volnychMist = value;
					this.SendPropertyChanged("volnychMist");
					this.OnvolnychMistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poznamka", DbType="NVarChar(MAX)")]
		public string poznamka
		{
			get
			{
				return this._poznamka;
			}
			set
			{
				if ((this._poznamka != value))
				{
					this.OnpoznamkaChanging(value);
					this.SendPropertyChanging();
					this._poznamka = value;
					this.SendPropertyChanged("poznamka");
					this.OnpoznamkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VM_relVmJazyk", Storage="_relVmJazyks", ThisKey="id", OtherKey="idVM")]
		public EntitySet<relVmJazyk> relVmJazyks
		{
			get
			{
				return this._relVmJazyks;
			}
			set
			{
				this._relVmJazyks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VM_relVmTypZ", Storage="_relVmTypZs", ThisKey="id", OtherKey="idVM")]
		public EntitySet<relVmTypZ> relVmTypZs
		{
			get
			{
				return this._relVmTypZs;
			}
			set
			{
				this._relVmTypZs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="prof_VM", Storage="_prof", ThisKey="idProf", OtherKey="id", IsForeignKey=true)]
		public prof prof
		{
			get
			{
				return this._prof.Entity;
			}
			set
			{
				prof previousValue = this._prof.Entity;
				if (((previousValue != value) 
							|| (this._prof.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._prof.Entity = null;
						previousValue.VMs.Remove(this);
					}
					this._prof.Entity = value;
					if ((value != null))
					{
						value.VMs.Add(this);
						this._idProf = value.id;
					}
					else
					{
						this._idProf = default(int);
					}
					this.SendPropertyChanged("prof");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="uradPrace_VM", Storage="_uradPrace", ThisKey="idUP", OtherKey="id", IsForeignKey=true)]
		public uradPrace uradPrace
		{
			get
			{
				return this._uradPrace.Entity;
			}
			set
			{
				uradPrace previousValue = this._uradPrace.Entity;
				if (((previousValue != value) 
							|| (this._uradPrace.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._uradPrace.Entity = null;
						previousValue.VMs.Remove(this);
					}
					this._uradPrace.Entity = value;
					if ((value != null))
					{
						value.VMs.Add(this);
						this._idUP = value.id;
					}
					else
					{
						this._idUP = default(int);
					}
					this.SendPropertyChanged("uradPrace");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_relVmJazyks(relVmJazyk entity)
		{
			this.SendPropertyChanging();
			entity.VM = this;
		}
		
		private void detach_relVmJazyks(relVmJazyk entity)
		{
			this.SendPropertyChanging();
			entity.VM = null;
		}
		
		private void attach_relVmTypZs(relVmTypZ entity)
		{
			this.SendPropertyChanging();
			entity.VM = this;
		}
		
		private void detach_relVmTypZs(relVmTypZ entity)
		{
			this.SendPropertyChanging();
			entity.VM = null;
		}
	}
	
	public partial class SelectOkresResult
	{
		
		private int _id;
		
		private string _name;
		
		public SelectOkresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	public partial class SelectJazykResult
	{
		
		private int _id;
		
		private string _name;
		
		private string _uroven;
		
		public SelectJazykResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uroven", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string uroven
		{
			get
			{
				return this._uroven;
			}
			set
			{
				if ((this._uroven != value))
				{
					this._uroven = value;
				}
			}
		}
	}
	
	public partial class SelectOborResult
	{
		
		private int _id;
		
		private string _name;
		
		public SelectOborResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	public partial class SelectSmenyResult
	{
		
		private int _id;
		
		private string _name;
		
		public SelectSmenyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	public partial class SelectVzdelaniResult
	{
		
		private int _id;
		
		private string _name;
		
		public SelectVzdelaniResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(250)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	public partial class SelectVMResult
	{
		
		private int _id;
		
		private string _kodUP;
		
		private int _idProf;
		
		private string _firma;
		
		private System.Nullable<int> _idSmena;
		
		private System.Nullable<int> _idVzdelani;
		
		private string _idPracVztah;
		
		private string _idObce;
		
		private string _kontakt;
		
		private System.Nullable<decimal> _mzdaOd;
		
		private System.Nullable<decimal> _mzdaDo;
		
		private string _mzdaType;
		
		private System.Nullable<System.DateTime> _terminOd;
		
		private System.Nullable<System.DateTime> _terminDo;
		
		private int _idUP;
		
		private System.Nullable<int> _modryKarty;
		
		private System.Nullable<int> _zamestnKarty;
		
		private System.Nullable<System.DateTime> _dateAktual;
		
		private int _volnychMist;
		
		private string _poznamka;
		
		public SelectVMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodUP", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string kodUP
		{
			get
			{
				return this._kodUP;
			}
			set
			{
				if ((this._kodUP != value))
				{
					this._kodUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProf", DbType="Int NOT NULL")]
		public int idProf
		{
			get
			{
				return this._idProf;
			}
			set
			{
				if ((this._idProf != value))
				{
					this._idProf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string firma
		{
			get
			{
				return this._firma;
			}
			set
			{
				if ((this._firma != value))
				{
					this._firma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSmena", DbType="Int")]
		public System.Nullable<int> idSmena
		{
			get
			{
				return this._idSmena;
			}
			set
			{
				if ((this._idSmena != value))
				{
					this._idSmena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVzdelani", DbType="Int")]
		public System.Nullable<int> idVzdelani
		{
			get
			{
				return this._idVzdelani;
			}
			set
			{
				if ((this._idVzdelani != value))
				{
					this._idVzdelani = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPracVztah", DbType="NVarChar(50)")]
		public string idPracVztah
		{
			get
			{
				return this._idPracVztah;
			}
			set
			{
				if ((this._idPracVztah != value))
				{
					this._idPracVztah = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idObce", DbType="NVarChar(30)")]
		public string idObce
		{
			get
			{
				return this._idObce;
			}
			set
			{
				if ((this._idObce != value))
				{
					this._idObce = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kontakt", DbType="NVarChar(250)")]
		public string kontakt
		{
			get
			{
				return this._kontakt;
			}
			set
			{
				if ((this._kontakt != value))
				{
					this._kontakt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzdaOd", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> mzdaOd
		{
			get
			{
				return this._mzdaOd;
			}
			set
			{
				if ((this._mzdaOd != value))
				{
					this._mzdaOd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzdaDo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> mzdaDo
		{
			get
			{
				return this._mzdaDo;
			}
			set
			{
				if ((this._mzdaDo != value))
				{
					this._mzdaDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzdaType", DbType="NVarChar(10)")]
		public string mzdaType
		{
			get
			{
				return this._mzdaType;
			}
			set
			{
				if ((this._mzdaType != value))
				{
					this._mzdaType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_terminOd", DbType="Date")]
		public System.Nullable<System.DateTime> terminOd
		{
			get
			{
				return this._terminOd;
			}
			set
			{
				if ((this._terminOd != value))
				{
					this._terminOd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_terminDo", DbType="Date")]
		public System.Nullable<System.DateTime> terminDo
		{
			get
			{
				return this._terminDo;
			}
			set
			{
				if ((this._terminDo != value))
				{
					this._terminDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUP", DbType="Int NOT NULL")]
		public int idUP
		{
			get
			{
				return this._idUP;
			}
			set
			{
				if ((this._idUP != value))
				{
					this._idUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modryKarty", DbType="Int")]
		public System.Nullable<int> modryKarty
		{
			get
			{
				return this._modryKarty;
			}
			set
			{
				if ((this._modryKarty != value))
				{
					this._modryKarty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zamestnKarty", DbType="Int")]
		public System.Nullable<int> zamestnKarty
		{
			get
			{
				return this._zamestnKarty;
			}
			set
			{
				if ((this._zamestnKarty != value))
				{
					this._zamestnKarty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateAktual", DbType="Date")]
		public System.Nullable<System.DateTime> dateAktual
		{
			get
			{
				return this._dateAktual;
			}
			set
			{
				if ((this._dateAktual != value))
				{
					this._dateAktual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volnychMist", DbType="Int NOT NULL")]
		public int volnychMist
		{
			get
			{
				return this._volnychMist;
			}
			set
			{
				if ((this._volnychMist != value))
				{
					this._volnychMist = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poznamka", DbType="NVarChar(MAX)")]
		public string poznamka
		{
			get
			{
				return this._poznamka;
			}
			set
			{
				if ((this._poznamka != value))
				{
					this._poznamka = value;
				}
			}
		}
	}
	
	public partial class SelectProfByOborResult
	{
		
		private int _id;
		
		private string _name;
		
		public SelectProfByOborResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(250)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	public partial class SelectVMByJazykResult
	{
		
		private int _idVM;
		
		public SelectVMByJazykResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVM", DbType="Int NOT NULL")]
		public int idVM
		{
			get
			{
				return this._idVM;
			}
			set
			{
				if ((this._idVM != value))
				{
					this._idVM = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
