<?xml version="1.0" encoding="utf-8"?><Database Name="workSearсher" Class="dataClassWorkDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TIAMU;Initial Catalog=workSearсher;Integrated Security=True" SettingsObjectName="DataModel.Properties.Settings" SettingsPropertyName="connectString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.coobec" Member="coobecs">
    <Type Name="coobec">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="psc" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="idObec" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="obec_coobec" Member="obec" ThisKey="idObec" OtherKey="id" Type="obec" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vzdelan" Member="vzdelans">
    <Type Name="vzdelan">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="kodUP" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.files" Member="files">
    <Type Name="file">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.jazyk" Member="jazyks">
    <Type Name="jazyk">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="kodUP" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="uroven" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="urovenId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="jazyk_relVmJazyk" Member="relVmJazyks" ThisKey="id" OtherKey="idJazyk" Type="relVmJazyk" />
    </Type>
  </Table>
  <Table Name="dbo.obec" Member="obecs">
    <Type Name="obec">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idOkres" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="obec_coobec" Member="coobecs" ThisKey="id" OtherKey="idObec" Type="coobec" />
      <Association Name="okre_obec" Member="okre" ThisKey="idOkres" OtherKey="id" Type="okre" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.obor" Member="obors">
    <Type Name="obor">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kodUp" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="obor_prof" Member="profs" ThisKey="id" OtherKey="idObor" Type="prof" />
    </Type>
  </Table>
  <Table Name="dbo.okres" Member="okres">
    <Type Name="okre">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kodUP" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="okre_obec" Member="obecs" ThisKey="id" OtherKey="idOkres" Type="obec" />
    </Type>
  </Table>
  <Table Name="dbo.pracVztah" Member="pracVztahs">
    <Type Name="pracVztah">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kod" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.prof" Member="profs">
    <Type Name="prof">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="kodUP" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="idObor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="prof_VM" Member="VMs" ThisKey="id" OtherKey="idProf" Type="VM" />
      <Association Name="obor_prof" Member="obor" ThisKey="idObor" OtherKey="id" Type="obor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.smeny" Member="smenies">
    <Type Name="smeny">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kodUP" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.typZamest" Member="typZamests">
    <Type Name="typZamest">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kod" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="typZamest_relVmTypZ" Member="relVmTypZs" ThisKey="id" OtherKey="idTypZ" Type="relVmTypZ" />
    </Type>
  </Table>
  <Table Name="dbo.uradPrace" Member="uradPraces">
    <Type Name="uradPrace">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kodUP" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="uradPrace_VM" Member="VMs" ThisKey="id" OtherKey="idUP" Type="VM" />
    </Type>
  </Table>
  <Table Name="dbo.relVmJazyk" Member="relVmJazyks">
    <Type Name="relVmJazyk">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idVM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idJazyk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="jazyk_relVmJazyk" Member="jazyk" ThisKey="idJazyk" OtherKey="id" Type="jazyk" IsForeignKey="true" />
      <Association Name="VM_relVmJazyk" Member="VM" ThisKey="idVM" OtherKey="id" Type="VM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.relVmTypZ" Member="relVmTypZs">
    <Type Name="relVmTypZ">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idVM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idTypZ" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="typZamest_relVmTypZ" Member="typZamest" ThisKey="idTypZ" OtherKey="id" Type="typZamest" IsForeignKey="true" />
      <Association Name="VM_relVmTypZ" Member="VM" ThisKey="idVM" OtherKey="id" Type="VM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VM" Member="VMs">
    <Type Name="VM">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="kodUP" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="idProf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firma" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="idSmena" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idVzdelani" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPracVztah" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idObce" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="kontakt" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="mzdaOd" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="mzdaDo" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="mzdaType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="terminOd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="terminDo" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="idUP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="modryKarty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="zamestnKarty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dateAktual" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="volnychMist" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="poznamka" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="VM_relVmJazyk" Member="relVmJazyks" ThisKey="id" OtherKey="idVM" Type="relVmJazyk" />
      <Association Name="VM_relVmTypZ" Member="relVmTypZs" ThisKey="id" OtherKey="idVM" Type="relVmTypZ" />
      <Association Name="prof_VM" Member="prof" ThisKey="idProf" OtherKey="id" Type="prof" IsForeignKey="true" />
      <Association Name="uradPrace_VM" Member="uradPrace" ThisKey="idUP" OtherKey="id" Type="uradPrace" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SelectOkres" Method="SelectOkres">
    <Parameter Name="okres" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectOkresResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectJazyk" Method="SelectJazyk">
    <Parameter Name="jazyk" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectJazykResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="uroven" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectObor" Method="SelectObor">
    <Parameter Name="obor" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectOborResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectSmeny" Method="SelectSmeny">
    <Parameter Name="smeny" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectSmenyResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectVzdelani" Method="SelectVzdelani">
    <Parameter Name="vzdelani" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectVzdelaniResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectVM" Method="SelectVM">
    <Parameter Name="VM" Parameter="vM" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectVMResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kodUP" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="idProf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firma" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="idSmena" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idVzdelani" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPracVztah" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idObce" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="kontakt" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="mzdaOd" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="mzdaDo" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="mzdaType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="terminOd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="terminDo" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="idUP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="modryKarty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="zamestnKarty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dateAktual" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="volnychMist" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="poznamka" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectProfByObor" Method="SelectProfByObor">
    <Parameter Name="obor" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectProfByOborResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectVMByJazyk" Method="SelectVMByJazyk">
    <Parameter Name="jazyk" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectVMByJazykResult">
      <Column Name="idVM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>